# Generated by Django 5.0.1 on 2024-01-11 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemStatements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('prerequisites', models.TextField(verbose_name='List of Prerequisites')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('not started', 'Not Started')], default='not started', max_length=50, verbose_name='Status')),
                ('mentors_applied', models.ManyToManyField(blank=True, related_name='applied_problem_statements', to='adminControl.mentorapplication')),
                ('mentors_assigned', models.ManyToManyField(blank=True, related_name='assigned_problem_statements', to='authentication.mentor')),
                ('students_working_on', models.ManyToManyField(blank=True, related_name='problems', to='authentication.student')),
            ],
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='problem_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminControl.problemstatements'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorapplication',
            unique_together={('mentor', 'problem_statement')},
        ),
    ]
