# Generated by Django 5.0.1 on 2024-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('prerequisites', models.TextField(verbose_name='List of Prerequisites')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('not started', 'Not Started')], default='not_started', max_length=50, verbose_name='Status')),
                ('students_working_on', models.ManyToManyField(blank=True, to='authentication.student')),
            ],
        ),
    ]
