# Generated by Django 5.0.1 on 2024-01-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('mentor_name', models.CharField(max_length=100, verbose_name='Mentor Name')),
                ('contact_mail', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('mentor_pic', models.ImageField(blank=True, null=True, upload_to='mentor_pics/', verbose_name='Mentor Picture')),
                ('prerequisites', models.TextField(verbose_name='List of Prerequisites')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
