# Generated by Django 5.0.1 on 2024-01-11 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatements',
            name='mentors_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_problem_statements', to='authentication.mentor'),
        ),
        migrations.AlterField(
            model_name='problemstatements',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('not started', 'Not Started')], default='not started', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='problemstatements',
            name='students_working_on',
            field=models.ManyToManyField(blank=True, related_name='problems', to='authentication.student'),
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=False)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.mentor')),
                ('problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminControl.problemstatements')),
            ],
        ),
        migrations.AddField(
            model_name='problemstatements',
            name='mentors_applied',
            field=models.ManyToManyField(blank=True, related_name='applied_problem_statements', to='adminControl.mentorapplication'),
        ),
    ]
