# Generated by Django 5.0.1 on 2024-01-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemstatements',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
