# Generated by Django 5.0.1 on 2024-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0002_problemstatements_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemstatements',
            name='mentor_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/mentor_pics/', verbose_name='Mentor Picture'),
        ),
    ]
