# Generated by Django 5.0.1 on 2024-01-11 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminControl', '0002_problemstatements_mentors_assigned_and_more'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorapplication',
            unique_together={('mentor', 'problem_statement')},
        ),
    ]
