# Generated by Django 5.0.1 on 2024-01-11 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('none', 'None'), ('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
